"""Regenerate the base paper's Figures 11--15 from committed artifacts.

Figures 11, 12, 13 and 15 use the existing aggregate traces in
``results/baseline.json``.  Figure 14 alone uses genuine per-seed dead-node
traces from ``results/baseline_per_seed.json`` and reports a two-sided,
pointwise 95% Student-t confidence interval across seeds.

    python3 src/plot_baseline_figures.py
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path

os.environ.setdefault(
    "MPLCONFIGDIR", str(Path(tempfile.gettempdir()) / "chirp-matplotlib")
)
os.environ.setdefault(
    "XDG_CACHE_HOME", str(Path(tempfile.gettempdir()) / "chirp-cache")
)

import matplotlib  # noqa: E402
matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402
import numpy as np  # noqa: E402
from scipy.stats import t  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BASELINE = ROOT / "results" / "baseline.json"
DEFAULT_PER_SEED = ROOT / "results" / "baseline_per_seed.json"
DEFAULT_OUTPUT = ROOT / "figures" / "baseline"

PROTOCOLS = ("LEACH", "LEACH-C", "HEED", "PSO", "GA", "CSGD-NET")
STYLES = {
    "LEACH":    {"color": "#0072B2", "linestyle": "--", "marker": "o"},
    "LEACH-C":  {"color": "#E69F00", "linestyle": "-.", "marker": "s"},
    "HEED":     {"color": "#009E73", "linestyle": ":",  "marker": "^"},
    "PSO":      {"color": "#D55E00", "linestyle": "-",  "marker": "D"},
    "GA":       {"color": "#CC79A7", "linestyle": "--", "marker": "v"},
    "CSGD-NET": {"color": "#222222", "linestyle": "-",  "marker": "P"},
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _load(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"required result artifact not found: {path}")
    return json.loads(path.read_text())


def _validate_protocols(data: dict, label: str) -> None:
    if tuple(data) != PROTOCOLS:
        raise ValueError(
            f"{label} protocols/order {tuple(data)} != expected {PROTOCOLS}"
        )


def _line_plot(series: dict, *, title: str, ylabel: str,
               output_stem: Path, ylim: tuple[float, float] | None = None) -> list[str]:
    fig, ax = plt.subplots(figsize=(7.2, 4.5), constrained_layout=True)
    for name in PROTOCOLS:
        rounds, values = series[name]
        ax.plot(
            rounds, values, label=name, linewidth=1.8, markersize=4,
            markevery=5, **STYLES[name],
        )
    ax.set(title=title, xlabel="Round", ylabel=ylabel, xlim=(0, 50))
    if ylim is not None:
        ax.set_ylim(*ylim)
    ax.set_xticks(np.arange(0, 51, 10))
    ax.grid(True, color="#b0b0b0", alpha=0.35, linewidth=0.6)
    ax.legend(ncol=3, fontsize=8.5, frameon=False, loc="best")
    return _save(fig, output_stem, title)


def _save(fig, stem: Path, title: str) -> list[str]:
    outputs = []
    for suffix in (".png", ".pdf"):
        path = stem.with_suffix(suffix)
        metadata = {"Title": title, "Author": "CHIRP project"}
        if suffix == ".png":
            metadata["Description"] = "Generated by src/plot_baseline_figures.py"
        else:
            metadata["Subject"] = "Reproduction of base-paper baseline figure"
        fig.savefig(path, dpi=300, metadata=metadata)
        outputs.append(path.name)
    plt.close(fig)
    return outputs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", type=Path, default=DEFAULT_BASELINE)
    ap.add_argument("--per-seed", type=Path, default=DEFAULT_PER_SEED)
    ap.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    ap.add_argument("--max-round", type=int, default=50)
    args = ap.parse_args()

    if args.max_round != 50:
        ap.error("these reproductions use the base paper's fixed round range 0--50")

    baseline = _load(args.baseline)
    per_seed = _load(args.per_seed)
    _validate_protocols(baseline, "baseline.json")
    _validate_protocols(per_seed.get("protocols", {}), "baseline_per_seed.json")

    meta = per_seed.get("_meta", {})
    n_nodes = int(meta.get("n_nodes", 0))
    n_seeds = int(meta.get("n_seeds", 0))
    if n_nodes != 100 or n_seeds < 2:
        raise ValueError(f"invalid per-seed metadata: n_nodes={n_nodes}, n_seeds={n_seeds}")
    if meta.get("seeds") != list(range(n_seeds)):
        raise ValueError("per-seed metadata does not contain contiguous seeds 0..n-1")

    args.output_dir.mkdir(parents=True, exist_ok=True)
    rounds = np.arange(args.max_round + 1)

    residual, alive, dead, packets = {}, {}, {}, {}
    for name in PROTOCOLS:
        rec = baseline[name]
        for key in ("residual", "alive", "packets"):
            if len(rec[key]) < args.max_round:
                raise ValueError(f"{name}.{key} has fewer than 50 rounds")
        residual[name] = (
            rounds,
            np.r_[float(meta["initial_energy_j"]), rec["residual"][:args.max_round]],
        )
        live_values = np.r_[n_nodes, rec["alive"][:args.max_round]]
        alive[name] = (rounds, live_values)
        dead[name] = (rounds, n_nodes - live_values)
        packets[name] = (rounds, np.r_[0.0, rec["packets"][:args.max_round]])

    figures = {}
    figures["fig11"] = _line_plot(
        residual,
        title="Mean residual energy per node",
        ylabel="Mean residual energy per node (J)",
        output_stem=args.output_dir / "fig11_mean_residual_energy_per_node",
        ylim=(0, float(meta["initial_energy_j"])),
    )
    figures["fig12"] = _line_plot(
        alive,
        title="Live vehicle nodes",
        ylabel="Mean number of live nodes",
        output_stem=args.output_dir / "fig12_live_nodes",
        ylim=(0, n_nodes),
    )
    figures["fig13"] = _line_plot(
        dead,
        title="Dead vehicle nodes",
        ylabel="Mean number of dead nodes",
        output_stem=args.output_dir / "fig13_dead_nodes",
        ylim=(0, n_nodes),
    )

    fig, ax = plt.subplots(figsize=(7.2, 4.5), constrained_layout=True)
    critical = float(t.ppf(0.975, df=n_seeds - 1))
    for name in PROTOCOLS:
        runs = per_seed["protocols"][name]
        if [run["seed"] for run in runs] != list(range(n_seeds)):
            raise ValueError(f"{name}: run seeds disagree with metadata")
        dead_by_seed = np.asarray(
            [run["dead"][:args.max_round] for run in runs], dtype=float
        )
        if dead_by_seed.shape != (n_seeds, args.max_round):
            raise ValueError(f"{name}: per-seed trace shape is {dead_by_seed.shape}")

        # Independent check: the rerun used for the CI must reproduce the
        # committed aggregate live-node trace exactly before it is plotted.
        reconstructed_alive = np.mean(n_nodes - dead_by_seed, axis=0)
        committed_alive = np.asarray(baseline[name]["alive"][:args.max_round])
        if not np.array_equal(reconstructed_alive, committed_alive):
            raise ValueError(f"{name}: per-seed mean does not reproduce baseline.json")

        mean = dead_by_seed.mean(axis=0)
        sem = dead_by_seed.std(axis=0, ddof=1) / np.sqrt(n_seeds)
        half_width = critical * sem
        mean = np.r_[0.0, mean]
        lower = np.r_[0.0, np.maximum(0.0, mean[1:] - half_width)]
        upper = np.r_[0.0, np.minimum(float(n_nodes), mean[1:] + half_width)]
        style = STYLES[name]
        ax.fill_between(
            rounds, lower, upper, color=style["color"], alpha=0.10, linewidth=0,
        )
        ax.plot(
            rounds, mean, label=name, linewidth=1.8, markersize=4,
            markevery=5, **style,
        )

    ax.set(
        title=f"Dead nodes with pointwise 95% confidence intervals ({n_seeds} seeds)",
        xlabel="Round", ylabel="Mean number of dead nodes",
        xlim=(0, 50), ylim=(0, n_nodes),
    )
    ax.set_xticks(np.arange(0, 51, 10))
    ax.grid(True, color="#b0b0b0", alpha=0.35, linewidth=0.6)
    ax.legend(ncol=3, fontsize=8.5, frameon=False, loc="best")
    figures["fig14"] = _save(
        fig, args.output_dir / "fig14_dead_nodes_95ci",
        f"Dead nodes with pointwise 95% confidence intervals ({n_seeds} seeds)",
    )

    figures["fig15"] = _line_plot(
        packets,
        title="Packets received by the RSU",
        ylabel="Mean cumulative packets delivered",
        output_stem=args.output_dir / "fig15_cumulative_packets_rsu",
    )

    manifest = {
        "generated_by": "python3 src/plot_baseline_figures.py",
        "sources": {
            str(args.baseline.relative_to(ROOT)): _sha256(args.baseline),
            str(args.per_seed.relative_to(ROOT)): _sha256(args.per_seed),
        },
        "protocols": list(PROTOCOLS),
        "rounds": [0, args.max_round],
        "fig14_ci": {
            "kind": "pointwise two-sided 95% Student-t confidence interval",
            "n_seeds": n_seeds,
            "degrees_of_freedom": n_seeds - 1,
            "critical_value": critical,
            "sample_standard_deviation_ddof": 1,
            "bounds": [0, n_nodes],
        },
        "figures": figures,
    }
    manifest_path = args.output_dir / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")

    print(f"source: {args.baseline} (Figures 11, 12, 13, 15; no rerun)")
    print(f"source: {args.per_seed} (Figure 14; {n_seeds} genuine seed traces)")
    for number, files in figures.items():
        print(f"{number}: {', '.join(files)}")
    print(f"manifest: {manifest_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
